### ISSUE TITLE
Organize files in one folder(Folder is "languages")

### ISSUE THREAD

**Issue by ViniciusDeep** [ViniciusDeep/Hello-Hacktober#115]

**Comment by GaminMatt** [comment]
Is this a separate folder for each language or just one folder?

**Comment by ViniciusDeep** [comment]
Just one folder with all hello worlds in any languages, after we make for each language

**Comment by ViniciusDeep** [comment]
Oooo @nai888  THANK YOU SO MUCH

**Comment by Soundug** [comment]
@ViniciusDeep Is this issue still open? 
I would like to fix this one. Separate out files of each programming language in each folder.

**Comment by nai888** [comment]
@Soundug people have continued putting files directly in the root directory after I fixed this, so yes, this is still an issue. 👍

As for separating them out per language, not sure if @ViniciusDeep wanted that or not.

**Comment by kirievalient** [comment]
@ViniciusDeep Is it possible for me to help out with this? 
I think everyone is still placing files into the root directory since the folders aren't completed

**Comment by tatendamarshall210** [comment]
place each file into its language folder and rename
